# Anna KaRNNa

In this notebook, I'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [4]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [5]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = sorted(set(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [6]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [7]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70])

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [8]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

In [9]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    characters_per_batch = n_seqs * n_steps
    n_batches = len(arr)//characters_per_batch
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * characters_per_batch]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [10]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [11]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 64 57 72 76 61 74  1 16  0]
 [ 1 57 69  1 70 71 76  1 63 71]
 [78 65 70 13  0  0  3 53 61 75]
 [70  1 60 77 74 65 70 63  1 64]
 [ 1 65 76  1 65 75 11  1 75 65]
 [ 1 37 76  1 79 57 75  0 71 70]
 [64 61 70  1 59 71 69 61  1 62]
 [26  1 58 77 76  1 70 71 79  1]
 [76  1 65 75 70  7 76 13  1 48]
 [ 1 75 57 65 60  1 76 71  1 64]]

y
 [[64 57 72 76 61 74  1 16  0  0]
 [57 69  1 70 71 76  1 63 71 65]
 [65 70 13  0  0  3 53 61 75 11]
 [ 1 60 77 74 65 70 63  1 64 65]
 [65 76  1 65 75 11  1 75 65 74]
 [37 76  1 79 57 75  0 71 70 68]
 [61 70  1 59 71 69 61  1 62 71]
 [ 1 58 77 76  1 70 71 79  1 75]
 [ 1 65 75 70  7 76 13  1 48 64]
 [75 57 65 60  1 76 71  1 64 61]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`.

In [12]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [13]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        
        # Add dropout to the cell
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$.

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

In [14]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    seq_output = tf.concat(lstm_output, axis=1)
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [15]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per batch_size per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [16]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

In [17]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here I'm defining the hyperparameters for the network. 

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.


In [18]:
batch_size = 100        # Sequences per batch
num_steps = 100         # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001   # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

In [19]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/20...  Training Step: 1...  Training loss: 4.4148...  3.9564 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.3220...  3.9424 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.7680...  3.9705 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 5.0242...  4.0075 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 4.0201...  4.3062 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.9036...  4.1666 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.7439...  4.1046 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.5857...  3.9805 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.4917...  4.1329 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.4313...  4.0328 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.4017...  4.0057 sec/batch
Epoch: 1/20...  Training Step: 12...  Training loss: 3.3947...  3.9519 sec/batch
Epoch: 1/20...  Training Step: 13... 

Epoch: 1/20...  Training Step: 103...  Training loss: 3.0971...  3.7942 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 3.0919...  3.8419 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 3.0794...  3.7107 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 3.0873...  3.8503 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 3.0631...  3.7585 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 3.0665...  3.8653 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 3.0835...  3.8103 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 3.0469...  3.9104 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 3.0602...  3.8655 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 3.0694...  3.7937 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 3.0453...  3.7417 sec/batch
Epoch: 1/20...  Training Step: 114...  Training loss: 3.0414...  3.7917 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 203...  Training loss: 2.4775...  3.8633 sec/batch
Epoch: 2/20...  Training Step: 204...  Training loss: 2.4705...  3.9825 sec/batch
Epoch: 2/20...  Training Step: 205...  Training loss: 2.4741...  3.8889 sec/batch
Epoch: 2/20...  Training Step: 206...  Training loss: 2.4732...  3.8248 sec/batch
Epoch: 2/20...  Training Step: 207...  Training loss: 2.4864...  3.8848 sec/batch
Epoch: 2/20...  Training Step: 208...  Training loss: 2.4600...  3.7039 sec/batch
Epoch: 2/20...  Training Step: 209...  Training loss: 2.4584...  3.8755 sec/batch
Epoch: 2/20...  Training Step: 210...  Training loss: 2.4631...  3.6878 sec/batch
Epoch: 2/20...  Training Step: 211...  Training loss: 2.4615...  3.9311 sec/batch
Epoch: 2/20...  Training Step: 212...  Training loss: 2.4884...  3.8129 sec/batch
Epoch: 2/20...  Training Step: 213...  Training loss: 2.4542...  3.8553 sec/batch
Epoch: 2/20...  Training Step: 214...  Training loss: 2.4489...  3.6916 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 303...  Training loss: 2.2122...  3.7512 sec/batch
Epoch: 2/20...  Training Step: 304...  Training loss: 2.2217...  3.9489 sec/batch
Epoch: 2/20...  Training Step: 305...  Training loss: 2.2153...  3.9554 sec/batch
Epoch: 2/20...  Training Step: 306...  Training loss: 2.2513...  3.9945 sec/batch
Epoch: 2/20...  Training Step: 307...  Training loss: 2.2322...  3.7662 sec/batch
Epoch: 2/20...  Training Step: 308...  Training loss: 2.2042...  3.9094 sec/batch
Epoch: 2/20...  Training Step: 309...  Training loss: 2.2179...  3.7367 sec/batch
Epoch: 2/20...  Training Step: 310...  Training loss: 2.2263...  3.8068 sec/batch
Epoch: 2/20...  Training Step: 311...  Training loss: 2.2123...  3.7270 sec/batch
Epoch: 2/20...  Training Step: 312...  Training loss: 2.1951...  3.9249 sec/batch
Epoch: 2/20...  Training Step: 313...  Training loss: 2.2015...  3.8283 sec/batch
Epoch: 2/20...  Training Step: 314...  Training loss: 2.1693...  3.8999 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 403...  Training loss: 2.0764...  3.8073 sec/batch
Epoch: 3/20...  Training Step: 404...  Training loss: 2.0635...  4.1248 sec/batch
Epoch: 3/20...  Training Step: 405...  Training loss: 2.0945...  4.5201 sec/batch
Epoch: 3/20...  Training Step: 406...  Training loss: 2.0569...  4.8976 sec/batch
Epoch: 3/20...  Training Step: 407...  Training loss: 2.0420...  4.7354 sec/batch
Epoch: 3/20...  Training Step: 408...  Training loss: 2.0380...  4.7644 sec/batch
Epoch: 3/20...  Training Step: 409...  Training loss: 2.0626...  4.4290 sec/batch
Epoch: 3/20...  Training Step: 410...  Training loss: 2.0949...  4.5992 sec/batch
Epoch: 3/20...  Training Step: 411...  Training loss: 2.0493...  4.2073 sec/batch
Epoch: 3/20...  Training Step: 412...  Training loss: 2.0347...  3.9124 sec/batch
Epoch: 3/20...  Training Step: 413...  Training loss: 2.0518...  4.5402 sec/batch
Epoch: 3/20...  Training Step: 414...  Training loss: 2.0878...  4.2754 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 503...  Training loss: 1.9406...  4.2648 sec/batch
Epoch: 3/20...  Training Step: 504...  Training loss: 1.9492...  4.0259 sec/batch
Epoch: 3/20...  Training Step: 505...  Training loss: 1.9555...  4.1757 sec/batch
Epoch: 3/20...  Training Step: 506...  Training loss: 1.9439...  4.0362 sec/batch
Epoch: 3/20...  Training Step: 507...  Training loss: 1.9404...  4.0586 sec/batch
Epoch: 3/20...  Training Step: 508...  Training loss: 1.9381...  4.2338 sec/batch
Epoch: 3/20...  Training Step: 509...  Training loss: 1.9434...  4.3810 sec/batch
Epoch: 3/20...  Training Step: 510...  Training loss: 1.9278...  4.3840 sec/batch
Epoch: 3/20...  Training Step: 511...  Training loss: 1.9264...  4.1702 sec/batch
Epoch: 3/20...  Training Step: 512...  Training loss: 1.8951...  4.2113 sec/batch
Epoch: 3/20...  Training Step: 513...  Training loss: 1.9387...  4.4601 sec/batch
Epoch: 3/20...  Training Step: 514...  Training loss: 1.9177...  4.2400 sec/batch
Epoch: 3/20...  

Epoch: 4/20...  Training Step: 603...  Training loss: 1.8905...  4.2033 sec/batch
Epoch: 4/20...  Training Step: 604...  Training loss: 1.8462...  4.1237 sec/batch
Epoch: 4/20...  Training Step: 605...  Training loss: 1.8288...  4.1252 sec/batch
Epoch: 4/20...  Training Step: 606...  Training loss: 1.8254...  4.0161 sec/batch
Epoch: 4/20...  Training Step: 607...  Training loss: 1.8487...  4.1672 sec/batch
Epoch: 4/20...  Training Step: 608...  Training loss: 1.8905...  4.2133 sec/batch
Epoch: 4/20...  Training Step: 609...  Training loss: 1.8336...  4.2563 sec/batch
Epoch: 4/20...  Training Step: 610...  Training loss: 1.8282...  4.2628 sec/batch
Epoch: 4/20...  Training Step: 611...  Training loss: 1.8542...  4.4751 sec/batch
Epoch: 4/20...  Training Step: 612...  Training loss: 1.8874...  4.4275 sec/batch
Epoch: 4/20...  Training Step: 613...  Training loss: 1.8605...  4.1872 sec/batch
Epoch: 4/20...  Training Step: 614...  Training loss: 1.8585...  4.1172 sec/batch
Epoch: 4/20...  

Epoch: 4/20...  Training Step: 703...  Training loss: 1.7745...  4.0721 sec/batch
Epoch: 4/20...  Training Step: 704...  Training loss: 1.7845...  4.0891 sec/batch
Epoch: 4/20...  Training Step: 705...  Training loss: 1.7702...  3.8643 sec/batch
Epoch: 4/20...  Training Step: 706...  Training loss: 1.7599...  4.0316 sec/batch
Epoch: 4/20...  Training Step: 707...  Training loss: 1.7667...  4.1611 sec/batch
Epoch: 4/20...  Training Step: 708...  Training loss: 1.7580...  4.1017 sec/batch
Epoch: 4/20...  Training Step: 709...  Training loss: 1.7436...  3.9980 sec/batch
Epoch: 4/20...  Training Step: 710...  Training loss: 1.7347...  4.2609 sec/batch
Epoch: 4/20...  Training Step: 711...  Training loss: 1.7712...  4.1617 sec/batch
Epoch: 4/20...  Training Step: 712...  Training loss: 1.7652...  4.2027 sec/batch
Epoch: 4/20...  Training Step: 713...  Training loss: 1.7701...  4.1802 sec/batch
Epoch: 4/20...  Training Step: 714...  Training loss: 1.7642...  4.0190 sec/batch
Epoch: 4/20...  

Epoch: 5/20...  Training Step: 803...  Training loss: 1.6851...  4.2728 sec/batch
Epoch: 5/20...  Training Step: 804...  Training loss: 1.6913...  4.4801 sec/batch
Epoch: 5/20...  Training Step: 805...  Training loss: 1.7061...  4.4561 sec/batch
Epoch: 5/20...  Training Step: 806...  Training loss: 1.7512...  4.2010 sec/batch
Epoch: 5/20...  Training Step: 807...  Training loss: 1.7047...  4.1882 sec/batch
Epoch: 5/20...  Training Step: 808...  Training loss: 1.6991...  4.2303 sec/batch
Epoch: 5/20...  Training Step: 809...  Training loss: 1.7150...  4.1453 sec/batch
Epoch: 5/20...  Training Step: 810...  Training loss: 1.7460...  4.1246 sec/batch
Epoch: 5/20...  Training Step: 811...  Training loss: 1.7218...  4.2273 sec/batch
Epoch: 5/20...  Training Step: 812...  Training loss: 1.7300...  4.3314 sec/batch
Epoch: 5/20...  Training Step: 813...  Training loss: 1.7008...  4.4606 sec/batch
Epoch: 5/20...  Training Step: 814...  Training loss: 1.7382...  4.2228 sec/batch
Epoch: 5/20...  

Epoch: 5/20...  Training Step: 903...  Training loss: 1.6487...  3.9009 sec/batch
Epoch: 5/20...  Training Step: 904...  Training loss: 1.6470...  4.6650 sec/batch
Epoch: 5/20...  Training Step: 905...  Training loss: 1.6520...  4.2073 sec/batch
Epoch: 5/20...  Training Step: 906...  Training loss: 1.6387...  4.2463 sec/batch
Epoch: 5/20...  Training Step: 907...  Training loss: 1.6282...  4.4741 sec/batch
Epoch: 5/20...  Training Step: 908...  Training loss: 1.6127...  4.1425 sec/batch
Epoch: 5/20...  Training Step: 909...  Training loss: 1.6615...  4.2583 sec/batch
Epoch: 5/20...  Training Step: 910...  Training loss: 1.6532...  4.1544 sec/batch
Epoch: 5/20...  Training Step: 911...  Training loss: 1.6463...  4.1021 sec/batch
Epoch: 5/20...  Training Step: 912...  Training loss: 1.6488...  4.1076 sec/batch
Epoch: 5/20...  Training Step: 913...  Training loss: 1.6522...  4.2479 sec/batch
Epoch: 5/20...  Training Step: 914...  Training loss: 1.6061...  4.1637 sec/batch
Epoch: 5/20...  

Epoch: 6/20...  Training Step: 1003...  Training loss: 1.6164...  3.9860 sec/batch
Epoch: 6/20...  Training Step: 1004...  Training loss: 1.6466...  4.0115 sec/batch
Epoch: 6/20...  Training Step: 1005...  Training loss: 1.5994...  4.0170 sec/batch
Epoch: 6/20...  Training Step: 1006...  Training loss: 1.5997...  3.9080 sec/batch
Epoch: 6/20...  Training Step: 1007...  Training loss: 1.6319...  4.1021 sec/batch
Epoch: 6/20...  Training Step: 1008...  Training loss: 1.6337...  4.4255 sec/batch
Epoch: 6/20...  Training Step: 1009...  Training loss: 1.6199...  4.0601 sec/batch
Epoch: 6/20...  Training Step: 1010...  Training loss: 1.6336...  3.9529 sec/batch
Epoch: 6/20...  Training Step: 1011...  Training loss: 1.5959...  4.0100 sec/batch
Epoch: 6/20...  Training Step: 1012...  Training loss: 1.6347...  3.9740 sec/batch
Epoch: 6/20...  Training Step: 1013...  Training loss: 1.6014...  3.9994 sec/batch
Epoch: 6/20...  Training Step: 1014...  Training loss: 1.6246...  4.1936 sec/batch
Epoc

Epoch: 6/20...  Training Step: 1102...  Training loss: 1.5683...  4.1734 sec/batch
Epoch: 6/20...  Training Step: 1103...  Training loss: 1.5645...  4.0375 sec/batch
Epoch: 6/20...  Training Step: 1104...  Training loss: 1.5590...  3.9079 sec/batch
Epoch: 6/20...  Training Step: 1105...  Training loss: 1.5467...  3.9810 sec/batch
Epoch: 6/20...  Training Step: 1106...  Training loss: 1.5330...  4.0235 sec/batch
Epoch: 6/20...  Training Step: 1107...  Training loss: 1.5750...  4.0145 sec/batch
Epoch: 6/20...  Training Step: 1108...  Training loss: 1.5685...  4.2140 sec/batch
Epoch: 6/20...  Training Step: 1109...  Training loss: 1.5668...  4.3504 sec/batch
Epoch: 6/20...  Training Step: 1110...  Training loss: 1.5588...  4.1126 sec/batch
Epoch: 6/20...  Training Step: 1111...  Training loss: 1.5686...  4.2042 sec/batch
Epoch: 6/20...  Training Step: 1112...  Training loss: 1.5288...  4.0721 sec/batch
Epoch: 6/20...  Training Step: 1113...  Training loss: 1.5180...  4.1126 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1201...  Training loss: 1.5501...  3.5775 sec/batch
Epoch: 7/20...  Training Step: 1202...  Training loss: 1.5802...  4.1086 sec/batch
Epoch: 7/20...  Training Step: 1203...  Training loss: 1.5344...  4.3790 sec/batch
Epoch: 7/20...  Training Step: 1204...  Training loss: 1.5291...  4.2929 sec/batch
Epoch: 7/20...  Training Step: 1205...  Training loss: 1.5537...  4.0506 sec/batch
Epoch: 7/20...  Training Step: 1206...  Training loss: 1.5767...  4.2143 sec/batch
Epoch: 7/20...  Training Step: 1207...  Training loss: 1.5512...  4.3375 sec/batch
Epoch: 7/20...  Training Step: 1208...  Training loss: 1.5652...  4.2720 sec/batch
Epoch: 7/20...  Training Step: 1209...  Training loss: 1.5323...  4.5407 sec/batch
Epoch: 7/20...  Training Step: 1210...  Training loss: 1.5604...  4.3294 sec/batch
Epoch: 7/20...  Training Step: 1211...  Training loss: 1.5327...  4.2906 sec/batch
Epoch: 7/20...  Training Step: 1212...  Training loss: 1.5481...  4.1432 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1300...  Training loss: 1.5040...  4.1613 sec/batch
Epoch: 7/20...  Training Step: 1301...  Training loss: 1.4995...  4.0606 sec/batch
Epoch: 7/20...  Training Step: 1302...  Training loss: 1.4815...  4.1706 sec/batch
Epoch: 7/20...  Training Step: 1303...  Training loss: 1.4804...  4.3439 sec/batch
Epoch: 7/20...  Training Step: 1304...  Training loss: 1.4546...  4.4070 sec/batch
Epoch: 7/20...  Training Step: 1305...  Training loss: 1.4957...  4.4546 sec/batch
Epoch: 7/20...  Training Step: 1306...  Training loss: 1.5001...  4.1532 sec/batch
Epoch: 7/20...  Training Step: 1307...  Training loss: 1.4971...  4.0856 sec/batch
Epoch: 7/20...  Training Step: 1308...  Training loss: 1.4799...  4.1852 sec/batch
Epoch: 7/20...  Training Step: 1309...  Training loss: 1.4948...  4.1882 sec/batch
Epoch: 7/20...  Training Step: 1310...  Training loss: 1.4569...  4.2533 sec/batch
Epoch: 7/20...  Training Step: 1311...  Training loss: 1.4438...  4.0501 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1399...  Training loss: 1.4674...  4.1732 sec/batch
Epoch: 8/20...  Training Step: 1400...  Training loss: 1.4975...  4.2069 sec/batch
Epoch: 8/20...  Training Step: 1401...  Training loss: 1.4653...  3.6425 sec/batch
Epoch: 8/20...  Training Step: 1402...  Training loss: 1.4514...  4.1987 sec/batch
Epoch: 8/20...  Training Step: 1403...  Training loss: 1.4813...  4.1066 sec/batch
Epoch: 8/20...  Training Step: 1404...  Training loss: 1.5026...  4.2702 sec/batch
Epoch: 8/20...  Training Step: 1405...  Training loss: 1.4862...  4.2829 sec/batch
Epoch: 8/20...  Training Step: 1406...  Training loss: 1.5016...  4.1847 sec/batch
Epoch: 8/20...  Training Step: 1407...  Training loss: 1.4611...  4.1532 sec/batch
Epoch: 8/20...  Training Step: 1408...  Training loss: 1.4953...  4.0631 sec/batch
Epoch: 8/20...  Training Step: 1409...  Training loss: 1.4619...  4.1392 sec/batch
Epoch: 8/20...  Training Step: 1410...  Training loss: 1.4881...  4.0938 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1498...  Training loss: 1.4514...  4.2429 sec/batch
Epoch: 8/20...  Training Step: 1499...  Training loss: 1.4471...  4.1567 sec/batch
Epoch: 8/20...  Training Step: 1500...  Training loss: 1.4261...  4.1051 sec/batch
Epoch: 8/20...  Training Step: 1501...  Training loss: 1.4212...  4.1051 sec/batch
Epoch: 8/20...  Training Step: 1502...  Training loss: 1.4115...  4.1787 sec/batch
Epoch: 8/20...  Training Step: 1503...  Training loss: 1.4452...  4.2850 sec/batch
Epoch: 8/20...  Training Step: 1504...  Training loss: 1.4478...  4.1763 sec/batch
Epoch: 8/20...  Training Step: 1505...  Training loss: 1.4359...  4.4216 sec/batch
Epoch: 8/20...  Training Step: 1506...  Training loss: 1.4314...  4.4440 sec/batch
Epoch: 8/20...  Training Step: 1507...  Training loss: 1.4413...  4.5036 sec/batch
Epoch: 8/20...  Training Step: 1508...  Training loss: 1.3980...  4.2049 sec/batch
Epoch: 8/20...  Training Step: 1509...  Training loss: 1.3897...  4.1412 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1597...  Training loss: 1.4110...  3.9324 sec/batch
Epoch: 9/20...  Training Step: 1598...  Training loss: 1.4457...  3.8508 sec/batch
Epoch: 9/20...  Training Step: 1599...  Training loss: 1.4172...  3.9024 sec/batch
Epoch: 9/20...  Training Step: 1600...  Training loss: 1.4083...  4.1617 sec/batch
Epoch: 9/20...  Training Step: 1601...  Training loss: 1.4315...  3.7702 sec/batch
Epoch: 9/20...  Training Step: 1602...  Training loss: 1.4420...  4.0255 sec/batch
Epoch: 9/20...  Training Step: 1603...  Training loss: 1.4323...  3.9675 sec/batch
Epoch: 9/20...  Training Step: 1604...  Training loss: 1.4548...  3.9975 sec/batch
Epoch: 9/20...  Training Step: 1605...  Training loss: 1.4233...  3.9630 sec/batch
Epoch: 9/20...  Training Step: 1606...  Training loss: 1.4320...  3.9856 sec/batch
Epoch: 9/20...  Training Step: 1607...  Training loss: 1.4176...  4.0756 sec/batch
Epoch: 9/20...  Training Step: 1608...  Training loss: 1.4265...  4.3199 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1696...  Training loss: 1.4059...  4.1887 sec/batch
Epoch: 9/20...  Training Step: 1697...  Training loss: 1.4053...  4.0741 sec/batch
Epoch: 9/20...  Training Step: 1698...  Training loss: 1.3901...  4.1462 sec/batch
Epoch: 9/20...  Training Step: 1699...  Training loss: 1.3823...  4.0060 sec/batch
Epoch: 9/20...  Training Step: 1700...  Training loss: 1.3760...  4.0946 sec/batch
Epoch: 9/20...  Training Step: 1701...  Training loss: 1.4027...  4.1860 sec/batch
Epoch: 9/20...  Training Step: 1702...  Training loss: 1.4072...  4.4000 sec/batch
Epoch: 9/20...  Training Step: 1703...  Training loss: 1.3899...  4.0981 sec/batch
Epoch: 9/20...  Training Step: 1704...  Training loss: 1.3937...  4.1172 sec/batch
Epoch: 9/20...  Training Step: 1705...  Training loss: 1.4035...  4.2073 sec/batch
Epoch: 9/20...  Training Step: 1706...  Training loss: 1.3579...  4.1922 sec/batch
Epoch: 9/20...  Training Step: 1707...  Training loss: 1.3548...  4.0956 sec/batch
Epoc

Epoch: 10/20...  Training Step: 1795...  Training loss: 1.3966...  4.3270 sec/batch
Epoch: 10/20...  Training Step: 1796...  Training loss: 1.4150...  4.2248 sec/batch
Epoch: 10/20...  Training Step: 1797...  Training loss: 1.3785...  4.1367 sec/batch
Epoch: 10/20...  Training Step: 1798...  Training loss: 1.3775...  4.0651 sec/batch
Epoch: 10/20...  Training Step: 1799...  Training loss: 1.4095...  4.0701 sec/batch
Epoch: 10/20...  Training Step: 1800...  Training loss: 1.4119...  4.0881 sec/batch
Epoch: 10/20...  Training Step: 1801...  Training loss: 1.3997...  3.7872 sec/batch
Epoch: 10/20...  Training Step: 1802...  Training loss: 1.4156...  4.3135 sec/batch
Epoch: 10/20...  Training Step: 1803...  Training loss: 1.3846...  4.3134 sec/batch
Epoch: 10/20...  Training Step: 1804...  Training loss: 1.4069...  4.3164 sec/batch
Epoch: 10/20...  Training Step: 1805...  Training loss: 1.3854...  4.2800 sec/batch
Epoch: 10/20...  Training Step: 1806...  Training loss: 1.4160...  4.3094 se

Epoch: 10/20...  Training Step: 1893...  Training loss: 1.3603...  4.0230 sec/batch
Epoch: 10/20...  Training Step: 1894...  Training loss: 1.3773...  4.0756 sec/batch
Epoch: 10/20...  Training Step: 1895...  Training loss: 1.3779...  4.2063 sec/batch
Epoch: 10/20...  Training Step: 1896...  Training loss: 1.3540...  4.3451 sec/batch
Epoch: 10/20...  Training Step: 1897...  Training loss: 1.3492...  4.1747 sec/batch
Epoch: 10/20...  Training Step: 1898...  Training loss: 1.3414...  4.0826 sec/batch
Epoch: 10/20...  Training Step: 1899...  Training loss: 1.3702...  4.3670 sec/batch
Epoch: 10/20...  Training Step: 1900...  Training loss: 1.3719...  4.1627 sec/batch
Epoch: 10/20...  Training Step: 1901...  Training loss: 1.3664...  4.0441 sec/batch
Epoch: 10/20...  Training Step: 1902...  Training loss: 1.3715...  4.0403 sec/batch
Epoch: 10/20...  Training Step: 1903...  Training loss: 1.3685...  4.1472 sec/batch
Epoch: 10/20...  Training Step: 1904...  Training loss: 1.3352...  4.2429 se

Epoch: 11/20...  Training Step: 1991...  Training loss: 1.3399...  4.2428 sec/batch
Epoch: 11/20...  Training Step: 1992...  Training loss: 1.3471...  4.1437 sec/batch
Epoch: 11/20...  Training Step: 1993...  Training loss: 1.3544...  4.1866 sec/batch
Epoch: 11/20...  Training Step: 1994...  Training loss: 1.3763...  4.2363 sec/batch
Epoch: 11/20...  Training Step: 1995...  Training loss: 1.3510...  4.1637 sec/batch
Epoch: 11/20...  Training Step: 1996...  Training loss: 1.3445...  4.0701 sec/batch
Epoch: 11/20...  Training Step: 1997...  Training loss: 1.3763...  4.3434 sec/batch
Epoch: 11/20...  Training Step: 1998...  Training loss: 1.3805...  4.5214 sec/batch
Epoch: 11/20...  Training Step: 1999...  Training loss: 1.3621...  4.0608 sec/batch
Epoch: 11/20...  Training Step: 2000...  Training loss: 1.3789...  4.0596 sec/batch
Epoch: 11/20...  Training Step: 2001...  Training loss: 1.3520...  3.8619 sec/batch
Epoch: 11/20...  Training Step: 2002...  Training loss: 1.3835...  4.1019 se

Epoch: 11/20...  Training Step: 2089...  Training loss: 1.3252...  4.2484 sec/batch
Epoch: 11/20...  Training Step: 2090...  Training loss: 1.3679...  4.2600 sec/batch
Epoch: 11/20...  Training Step: 2091...  Training loss: 1.3402...  4.2733 sec/batch
Epoch: 11/20...  Training Step: 2092...  Training loss: 1.3479...  4.6638 sec/batch
Epoch: 11/20...  Training Step: 2093...  Training loss: 1.3443...  4.2035 sec/batch
Epoch: 11/20...  Training Step: 2094...  Training loss: 1.3338...  4.0761 sec/batch
Epoch: 11/20...  Training Step: 2095...  Training loss: 1.3174...  4.0986 sec/batch
Epoch: 11/20...  Training Step: 2096...  Training loss: 1.3062...  4.1914 sec/batch
Epoch: 11/20...  Training Step: 2097...  Training loss: 1.3428...  4.0916 sec/batch
Epoch: 11/20...  Training Step: 2098...  Training loss: 1.3569...  4.0961 sec/batch
Epoch: 11/20...  Training Step: 2099...  Training loss: 1.3279...  4.2163 sec/batch
Epoch: 11/20...  Training Step: 2100...  Training loss: 1.3474...  4.3404 se

Epoch: 12/20...  Training Step: 2187...  Training loss: 1.3456...  4.1307 sec/batch
Epoch: 12/20...  Training Step: 2188...  Training loss: 1.3309...  4.0811 sec/batch
Epoch: 12/20...  Training Step: 2189...  Training loss: 1.3257...  4.2548 sec/batch
Epoch: 12/20...  Training Step: 2190...  Training loss: 1.3287...  4.1807 sec/batch
Epoch: 12/20...  Training Step: 2191...  Training loss: 1.3304...  4.2027 sec/batch
Epoch: 12/20...  Training Step: 2192...  Training loss: 1.3517...  4.0335 sec/batch
Epoch: 12/20...  Training Step: 2193...  Training loss: 1.3239...  4.3089 sec/batch
Epoch: 12/20...  Training Step: 2194...  Training loss: 1.3243...  4.3990 sec/batch
Epoch: 12/20...  Training Step: 2195...  Training loss: 1.3545...  4.2568 sec/batch
Epoch: 12/20...  Training Step: 2196...  Training loss: 1.3607...  4.2578 sec/batch
Epoch: 12/20...  Training Step: 2197...  Training loss: 1.3470...  4.1181 sec/batch
Epoch: 12/20...  Training Step: 2198...  Training loss: 1.3593...  4.1482 se

Epoch: 12/20...  Training Step: 2285...  Training loss: 1.3255...  4.2234 sec/batch
Epoch: 12/20...  Training Step: 2286...  Training loss: 1.3369...  4.3039 sec/batch
Epoch: 12/20...  Training Step: 2287...  Training loss: 1.3170...  4.3900 sec/batch
Epoch: 12/20...  Training Step: 2288...  Training loss: 1.3300...  4.5196 sec/batch
Epoch: 12/20...  Training Step: 2289...  Training loss: 1.3094...  4.2414 sec/batch
Epoch: 12/20...  Training Step: 2290...  Training loss: 1.3284...  4.1637 sec/batch
Epoch: 12/20...  Training Step: 2291...  Training loss: 1.3146...  4.0596 sec/batch
Epoch: 12/20...  Training Step: 2292...  Training loss: 1.3112...  4.0971 sec/batch
Epoch: 12/20...  Training Step: 2293...  Training loss: 1.2978...  4.2453 sec/batch
Epoch: 12/20...  Training Step: 2294...  Training loss: 1.2892...  4.2949 sec/batch
Epoch: 12/20...  Training Step: 2295...  Training loss: 1.3290...  4.4336 sec/batch
Epoch: 12/20...  Training Step: 2296...  Training loss: 1.3285...  4.2610 se

Epoch: 13/20...  Training Step: 2383...  Training loss: 1.3230...  4.2383 sec/batch
Epoch: 13/20...  Training Step: 2384...  Training loss: 1.3099...  4.1136 sec/batch
Epoch: 13/20...  Training Step: 2385...  Training loss: 1.3237...  4.0372 sec/batch
Epoch: 13/20...  Training Step: 2386...  Training loss: 1.3091...  4.2596 sec/batch
Epoch: 13/20...  Training Step: 2387...  Training loss: 1.2956...  4.4141 sec/batch
Epoch: 13/20...  Training Step: 2388...  Training loss: 1.3062...  4.3660 sec/batch
Epoch: 13/20...  Training Step: 2389...  Training loss: 1.3225...  4.2589 sec/batch
Epoch: 13/20...  Training Step: 2390...  Training loss: 1.3271...  3.9800 sec/batch
Epoch: 13/20...  Training Step: 2391...  Training loss: 1.2962...  4.3059 sec/batch
Epoch: 13/20...  Training Step: 2392...  Training loss: 1.2927...  3.9780 sec/batch
Epoch: 13/20...  Training Step: 2393...  Training loss: 1.3323...  4.0596 sec/batch
Epoch: 13/20...  Training Step: 2394...  Training loss: 1.3415...  3.9309 se

Epoch: 13/20...  Training Step: 2481...  Training loss: 1.2896...  4.2198 sec/batch
Epoch: 13/20...  Training Step: 2482...  Training loss: 1.2971...  4.3569 sec/batch
Epoch: 13/20...  Training Step: 2483...  Training loss: 1.3103...  4.3940 sec/batch
Epoch: 13/20...  Training Step: 2484...  Training loss: 1.3062...  4.3915 sec/batch
Epoch: 13/20...  Training Step: 2485...  Training loss: 1.2886...  4.2779 sec/batch
Epoch: 13/20...  Training Step: 2486...  Training loss: 1.3149...  4.0355 sec/batch
Epoch: 13/20...  Training Step: 2487...  Training loss: 1.2945...  4.3960 sec/batch
Epoch: 13/20...  Training Step: 2488...  Training loss: 1.3121...  4.1612 sec/batch
Epoch: 13/20...  Training Step: 2489...  Training loss: 1.3024...  4.3379 sec/batch
Epoch: 13/20...  Training Step: 2490...  Training loss: 1.2955...  4.2213 sec/batch
Epoch: 13/20...  Training Step: 2491...  Training loss: 1.2790...  3.9858 sec/batch
Epoch: 13/20...  Training Step: 2492...  Training loss: 1.2680...  3.9690 se

Epoch: 14/20...  Training Step: 2579...  Training loss: 1.2817...  4.1577 sec/batch
Epoch: 14/20...  Training Step: 2580...  Training loss: 1.2711...  4.0215 sec/batch
Epoch: 14/20...  Training Step: 2581...  Training loss: 1.3095...  4.2728 sec/batch
Epoch: 14/20...  Training Step: 2582...  Training loss: 1.2870...  4.1847 sec/batch
Epoch: 14/20...  Training Step: 2583...  Training loss: 1.3003...  4.3024 sec/batch
Epoch: 14/20...  Training Step: 2584...  Training loss: 1.2900...  4.0966 sec/batch
Epoch: 14/20...  Training Step: 2585...  Training loss: 1.2869...  4.2598 sec/batch
Epoch: 14/20...  Training Step: 2586...  Training loss: 1.2926...  4.1026 sec/batch
Epoch: 14/20...  Training Step: 2587...  Training loss: 1.2929...  4.0926 sec/batch
Epoch: 14/20...  Training Step: 2588...  Training loss: 1.3187...  4.1317 sec/batch
Epoch: 14/20...  Training Step: 2589...  Training loss: 1.2882...  4.0511 sec/batch
Epoch: 14/20...  Training Step: 2590...  Training loss: 1.2788...  4.3184 se

Epoch: 14/20...  Training Step: 2677...  Training loss: 1.2921...  4.2723 sec/batch
Epoch: 14/20...  Training Step: 2678...  Training loss: 1.2954...  4.1712 sec/batch
Epoch: 14/20...  Training Step: 2679...  Training loss: 1.2743...  4.0791 sec/batch
Epoch: 14/20...  Training Step: 2680...  Training loss: 1.2720...  4.1495 sec/batch
Epoch: 14/20...  Training Step: 2681...  Training loss: 1.2914...  4.1137 sec/batch
Epoch: 14/20...  Training Step: 2682...  Training loss: 1.3018...  4.3660 sec/batch
Epoch: 14/20...  Training Step: 2683...  Training loss: 1.2663...  4.0847 sec/batch
Epoch: 14/20...  Training Step: 2684...  Training loss: 1.3048...  4.1362 sec/batch
Epoch: 14/20...  Training Step: 2685...  Training loss: 1.2708...  4.2663 sec/batch
Epoch: 14/20...  Training Step: 2686...  Training loss: 1.2930...  4.0881 sec/batch
Epoch: 14/20...  Training Step: 2687...  Training loss: 1.2895...  4.1287 sec/batch
Epoch: 14/20...  Training Step: 2688...  Training loss: 1.2705...  4.2163 se

Epoch: 15/20...  Training Step: 2775...  Training loss: 1.2823...  4.0355 sec/batch
Epoch: 15/20...  Training Step: 2776...  Training loss: 1.3031...  4.2309 sec/batch
Epoch: 15/20...  Training Step: 2777...  Training loss: 1.2663...  3.9760 sec/batch
Epoch: 15/20...  Training Step: 2778...  Training loss: 1.2518...  4.3104 sec/batch
Epoch: 15/20...  Training Step: 2779...  Training loss: 1.2863...  4.4956 sec/batch
Epoch: 15/20...  Training Step: 2780...  Training loss: 1.2711...  4.1302 sec/batch
Epoch: 15/20...  Training Step: 2781...  Training loss: 1.2945...  4.0170 sec/batch
Epoch: 15/20...  Training Step: 2782...  Training loss: 1.2753...  4.1867 sec/batch
Epoch: 15/20...  Training Step: 2783...  Training loss: 1.2725...  4.1212 sec/batch
Epoch: 15/20...  Training Step: 2784...  Training loss: 1.2745...  4.0481 sec/batch
Epoch: 15/20...  Training Step: 2785...  Training loss: 1.2824...  4.2133 sec/batch
Epoch: 15/20...  Training Step: 2786...  Training loss: 1.2989...  4.7111 se

Epoch: 15/20...  Training Step: 2873...  Training loss: 1.2785...  4.4916 sec/batch
Epoch: 15/20...  Training Step: 2874...  Training loss: 1.2700...  4.1917 sec/batch
Epoch: 15/20...  Training Step: 2875...  Training loss: 1.2817...  4.1616 sec/batch
Epoch: 15/20...  Training Step: 2876...  Training loss: 1.2696...  4.0355 sec/batch
Epoch: 15/20...  Training Step: 2877...  Training loss: 1.2679...  4.0350 sec/batch
Epoch: 15/20...  Training Step: 2878...  Training loss: 1.2546...  4.2874 sec/batch
Epoch: 15/20...  Training Step: 2879...  Training loss: 1.2791...  4.2819 sec/batch
Epoch: 15/20...  Training Step: 2880...  Training loss: 1.2817...  4.4611 sec/batch
Epoch: 15/20...  Training Step: 2881...  Training loss: 1.2527...  4.2463 sec/batch
Epoch: 15/20...  Training Step: 2882...  Training loss: 1.2979...  4.2119 sec/batch
Epoch: 15/20...  Training Step: 2883...  Training loss: 1.2602...  4.1809 sec/batch
Epoch: 15/20...  Training Step: 2884...  Training loss: 1.2816...  4.2265 se

Epoch: 16/20...  Training Step: 2971...  Training loss: 1.4006...  4.4122 sec/batch
Epoch: 16/20...  Training Step: 2972...  Training loss: 1.2894...  4.2874 sec/batch
Epoch: 16/20...  Training Step: 2973...  Training loss: 1.2719...  4.4686 sec/batch
Epoch: 16/20...  Training Step: 2974...  Training loss: 1.2916...  4.7039 sec/batch
Epoch: 16/20...  Training Step: 2975...  Training loss: 1.2610...  4.3119 sec/batch
Epoch: 16/20...  Training Step: 2976...  Training loss: 1.2403...  4.2499 sec/batch
Epoch: 16/20...  Training Step: 2977...  Training loss: 1.2671...  4.2306 sec/batch
Epoch: 16/20...  Training Step: 2978...  Training loss: 1.2612...  4.3054 sec/batch
Epoch: 16/20...  Training Step: 2979...  Training loss: 1.2799...  4.2198 sec/batch
Epoch: 16/20...  Training Step: 2980...  Training loss: 1.2679...  4.3024 sec/batch
Epoch: 16/20...  Training Step: 2981...  Training loss: 1.2655...  4.6083 sec/batch
Epoch: 16/20...  Training Step: 2982...  Training loss: 1.2749...  4.7344 se

Epoch: 16/20...  Training Step: 3069...  Training loss: 1.2437...  4.5407 sec/batch
Epoch: 16/20...  Training Step: 3070...  Training loss: 1.2341...  4.3271 sec/batch
Epoch: 16/20...  Training Step: 3071...  Training loss: 1.2651...  4.4965 sec/batch
Epoch: 16/20...  Training Step: 3072...  Training loss: 1.2509...  4.3469 sec/batch
Epoch: 16/20...  Training Step: 3073...  Training loss: 1.2565...  4.4279 sec/batch
Epoch: 16/20...  Training Step: 3074...  Training loss: 1.2535...  4.6937 sec/batch
Epoch: 16/20...  Training Step: 3075...  Training loss: 1.2605...  4.8133 sec/batch
Epoch: 16/20...  Training Step: 3076...  Training loss: 1.2565...  4.5116 sec/batch
Epoch: 16/20...  Training Step: 3077...  Training loss: 1.2674...  4.4421 sec/batch
Epoch: 16/20...  Training Step: 3078...  Training loss: 1.2646...  4.2663 sec/batch
Epoch: 16/20...  Training Step: 3079...  Training loss: 1.2388...  4.4020 sec/batch
Epoch: 16/20...  Training Step: 3080...  Training loss: 1.2746...  4.2517 se

Epoch: 16/20...  Training Step: 3167...  Training loss: 1.2517...  4.2358 sec/batch
Epoch: 16/20...  Training Step: 3168...  Training loss: 1.2513...  4.3665 sec/batch
Epoch: 17/20...  Training Step: 3169...  Training loss: 1.3727...  4.4294 sec/batch
Epoch: 17/20...  Training Step: 3170...  Training loss: 1.2633...  4.3374 sec/batch
Epoch: 17/20...  Training Step: 3171...  Training loss: 1.2578...  4.3322 sec/batch
Epoch: 17/20...  Training Step: 3172...  Training loss: 1.2713...  4.1382 sec/batch
Epoch: 17/20...  Training Step: 3173...  Training loss: 1.2312...  4.2953 sec/batch
Epoch: 17/20...  Training Step: 3174...  Training loss: 1.2216...  4.2503 sec/batch
Epoch: 17/20...  Training Step: 3175...  Training loss: 1.2555...  4.3885 sec/batch
Epoch: 17/20...  Training Step: 3176...  Training loss: 1.2540...  4.4646 sec/batch
Epoch: 17/20...  Training Step: 3177...  Training loss: 1.2645...  4.2268 sec/batch
Epoch: 17/20...  Training Step: 3178...  Training loss: 1.2580...  4.2659 se

Epoch: 17/20...  Training Step: 3265...  Training loss: 1.2573...  4.1467 sec/batch
Epoch: 17/20...  Training Step: 3266...  Training loss: 1.2207...  4.1827 sec/batch
Epoch: 17/20...  Training Step: 3267...  Training loss: 1.2286...  4.1302 sec/batch
Epoch: 17/20...  Training Step: 3268...  Training loss: 1.2264...  4.0976 sec/batch
Epoch: 17/20...  Training Step: 3269...  Training loss: 1.2478...  4.3395 sec/batch
Epoch: 17/20...  Training Step: 3270...  Training loss: 1.2454...  4.4965 sec/batch
Epoch: 17/20...  Training Step: 3271...  Training loss: 1.2552...  4.2033 sec/batch
Epoch: 17/20...  Training Step: 3272...  Training loss: 1.2510...  4.2368 sec/batch
Epoch: 17/20...  Training Step: 3273...  Training loss: 1.2421...  4.0922 sec/batch
Epoch: 17/20...  Training Step: 3274...  Training loss: 1.2426...  4.1847 sec/batch
Epoch: 17/20...  Training Step: 3275...  Training loss: 1.2609...  4.2308 sec/batch
Epoch: 17/20...  Training Step: 3276...  Training loss: 1.2607...  4.3204 se

Epoch: 17/20...  Training Step: 3363...  Training loss: 1.2149...  4.1106 sec/batch
Epoch: 17/20...  Training Step: 3364...  Training loss: 1.2495...  4.1873 sec/batch
Epoch: 17/20...  Training Step: 3365...  Training loss: 1.2427...  4.1101 sec/batch
Epoch: 17/20...  Training Step: 3366...  Training loss: 1.2337...  4.2648 sec/batch
Epoch: 18/20...  Training Step: 3367...  Training loss: 1.3628...  4.1108 sec/batch
Epoch: 18/20...  Training Step: 3368...  Training loss: 1.2681...  3.9980 sec/batch
Epoch: 18/20...  Training Step: 3369...  Training loss: 1.2507...  4.2037 sec/batch
Epoch: 18/20...  Training Step: 3370...  Training loss: 1.2730...  4.0842 sec/batch
Epoch: 18/20...  Training Step: 3371...  Training loss: 1.2313...  4.5041 sec/batch
Epoch: 18/20...  Training Step: 3372...  Training loss: 1.2115...  4.2474 sec/batch
Epoch: 18/20...  Training Step: 3373...  Training loss: 1.2421...  4.1222 sec/batch
Epoch: 18/20...  Training Step: 3374...  Training loss: 1.2441...  4.2639 se

Epoch: 18/20...  Training Step: 3461...  Training loss: 1.2250...  4.1857 sec/batch
Epoch: 18/20...  Training Step: 3462...  Training loss: 1.2570...  4.1262 sec/batch
Epoch: 18/20...  Training Step: 3463...  Training loss: 1.2386...  4.2488 sec/batch
Epoch: 18/20...  Training Step: 3464...  Training loss: 1.2122...  4.2672 sec/batch
Epoch: 18/20...  Training Step: 3465...  Training loss: 1.2288...  4.2651 sec/batch
Epoch: 18/20...  Training Step: 3466...  Training loss: 1.2231...  4.1833 sec/batch
Epoch: 18/20...  Training Step: 3467...  Training loss: 1.2339...  4.1322 sec/batch
Epoch: 18/20...  Training Step: 3468...  Training loss: 1.2279...  4.1957 sec/batch
Epoch: 18/20...  Training Step: 3469...  Training loss: 1.2368...  4.1492 sec/batch
Epoch: 18/20...  Training Step: 3470...  Training loss: 1.2363...  4.1582 sec/batch
Epoch: 18/20...  Training Step: 3471...  Training loss: 1.2305...  4.2278 sec/batch
Epoch: 18/20...  Training Step: 3472...  Training loss: 1.2263...  4.2240 se

Epoch: 18/20...  Training Step: 3559...  Training loss: 1.2355...  4.6543 sec/batch
Epoch: 18/20...  Training Step: 3560...  Training loss: 1.2097...  4.2974 sec/batch
Epoch: 18/20...  Training Step: 3561...  Training loss: 1.1904...  4.2288 sec/batch
Epoch: 18/20...  Training Step: 3562...  Training loss: 1.2333...  4.1507 sec/batch
Epoch: 18/20...  Training Step: 3563...  Training loss: 1.2310...  4.1253 sec/batch
Epoch: 18/20...  Training Step: 3564...  Training loss: 1.2293...  4.2628 sec/batch
Epoch: 19/20...  Training Step: 3565...  Training loss: 1.3440...  4.1753 sec/batch
Epoch: 19/20...  Training Step: 3566...  Training loss: 1.2550...  4.3449 sec/batch
Epoch: 19/20...  Training Step: 3567...  Training loss: 1.2364...  4.5006 sec/batch
Epoch: 19/20...  Training Step: 3568...  Training loss: 1.2664...  4.3119 sec/batch
Epoch: 19/20...  Training Step: 3569...  Training loss: 1.2209...  4.0210 sec/batch
Epoch: 19/20...  Training Step: 3570...  Training loss: 1.2033...  4.0556 se

Epoch: 19/20...  Training Step: 3657...  Training loss: 1.2070...  4.0901 sec/batch
Epoch: 19/20...  Training Step: 3658...  Training loss: 1.2019...  4.2904 sec/batch
Epoch: 19/20...  Training Step: 3659...  Training loss: 1.2112...  4.1546 sec/batch
Epoch: 19/20...  Training Step: 3660...  Training loss: 1.2486...  4.3004 sec/batch
Epoch: 19/20...  Training Step: 3661...  Training loss: 1.2257...  4.4566 sec/batch
Epoch: 19/20...  Training Step: 3662...  Training loss: 1.1996...  4.3174 sec/batch
Epoch: 19/20...  Training Step: 3663...  Training loss: 1.2069...  4.2633 sec/batch
Epoch: 19/20...  Training Step: 3664...  Training loss: 1.2129...  4.2054 sec/batch
Epoch: 19/20...  Training Step: 3665...  Training loss: 1.2360...  4.2037 sec/batch
Epoch: 19/20...  Training Step: 3666...  Training loss: 1.2178...  4.1422 sec/batch
Epoch: 19/20...  Training Step: 3667...  Training loss: 1.2414...  4.4381 sec/batch
Epoch: 19/20...  Training Step: 3668...  Training loss: 1.2232...  4.4315 se

Epoch: 19/20...  Training Step: 3755...  Training loss: 1.1998...  4.1992 sec/batch
Epoch: 19/20...  Training Step: 3756...  Training loss: 1.2039...  4.2618 sec/batch
Epoch: 19/20...  Training Step: 3757...  Training loss: 1.2334...  4.0571 sec/batch
Epoch: 19/20...  Training Step: 3758...  Training loss: 1.2141...  4.1777 sec/batch
Epoch: 19/20...  Training Step: 3759...  Training loss: 1.1953...  4.0586 sec/batch
Epoch: 19/20...  Training Step: 3760...  Training loss: 1.2271...  4.1578 sec/batch
Epoch: 19/20...  Training Step: 3761...  Training loss: 1.2264...  4.4045 sec/batch
Epoch: 19/20...  Training Step: 3762...  Training loss: 1.2100...  4.1622 sec/batch
Epoch: 20/20...  Training Step: 3763...  Training loss: 1.3302...  4.1242 sec/batch
Epoch: 20/20...  Training Step: 3764...  Training loss: 1.2320...  4.0065 sec/batch
Epoch: 20/20...  Training Step: 3765...  Training loss: 1.2150...  4.0596 sec/batch
Epoch: 20/20...  Training Step: 3766...  Training loss: 1.2476...  3.9825 se

Epoch: 20/20...  Training Step: 3853...  Training loss: 1.1973...  3.9762 sec/batch
Epoch: 20/20...  Training Step: 3854...  Training loss: 1.2141...  3.9835 sec/batch
Epoch: 20/20...  Training Step: 3855...  Training loss: 1.1919...  4.3158 sec/batch
Epoch: 20/20...  Training Step: 3856...  Training loss: 1.1951...  4.2061 sec/batch
Epoch: 20/20...  Training Step: 3857...  Training loss: 1.2064...  4.1916 sec/batch
Epoch: 20/20...  Training Step: 3858...  Training loss: 1.2238...  3.9335 sec/batch
Epoch: 20/20...  Training Step: 3859...  Training loss: 1.2302...  4.0431 sec/batch
Epoch: 20/20...  Training Step: 3860...  Training loss: 1.1915...  3.9285 sec/batch
Epoch: 20/20...  Training Step: 3861...  Training loss: 1.1969...  4.0944 sec/batch
Epoch: 20/20...  Training Step: 3862...  Training loss: 1.1987...  4.1357 sec/batch
Epoch: 20/20...  Training Step: 3863...  Training loss: 1.2227...  4.4067 sec/batch
Epoch: 20/20...  Training Step: 3864...  Training loss: 1.2167...  4.0634 se

Epoch: 20/20...  Training Step: 3951...  Training loss: 1.2124...  3.9635 sec/batch
Epoch: 20/20...  Training Step: 3952...  Training loss: 1.2166...  4.0631 sec/batch
Epoch: 20/20...  Training Step: 3953...  Training loss: 1.1958...  3.9139 sec/batch
Epoch: 20/20...  Training Step: 3954...  Training loss: 1.1954...  4.1757 sec/batch
Epoch: 20/20...  Training Step: 3955...  Training loss: 1.2155...  4.1251 sec/batch
Epoch: 20/20...  Training Step: 3956...  Training loss: 1.2022...  4.2083 sec/batch
Epoch: 20/20...  Training Step: 3957...  Training loss: 1.1812...  4.0486 sec/batch
Epoch: 20/20...  Training Step: 3958...  Training loss: 1.2194...  4.1086 sec/batch
Epoch: 20/20...  Training Step: 3959...  Training loss: 1.2068...  4.0551 sec/batch
Epoch: 20/20...  Training Step: 3960...  Training loss: 1.2144...  4.0390 sec/batch


#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [20]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints\\i3960_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3200_l512.ckpt"
all_mo

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [21]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [22]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [23]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints\\i3960_l512.ckpt'

In [24]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints\i3960_l512.ckpt
Fartiov was a
personage, who was all the sound of that man whose thought to her so
such a patient face as a little fellow.

They saw this to him; and at the stoussess of the day he had all so that
his brain. She was not a station.

"Why so? What am I to say," she said, with a smile of taking her, and the master
and her father assented, and with a firm time was, and she, then a children
of the mild that had been a sense of answer to at the table--he was said and
was not sitting to the same that the society--that he could not coll
conversation about his feelings only in the country and she was noise and
missake by the storm to him of him, and she was trivial to him to him.

Anna had so surprised before the contrary of her heart. The members of
the same way and himself and men of that she had thought of her heart
with him to the close times at the cheeks on his wife. All he shaded ov
himself.

"That's that myself, but y

In [25]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i200_l512.ckpt
Farg of inlo herantad toute has thit sith tha sandesig ha hased andes ated and there to tha hes ore the whe ald the te ant he tomatins hot on the sar alid on toth thes herasse this ho hir thasd afilt we the sime sout the as sing ther oud harin has
oussand the
sint on sas ife he tather sous tand sis ot inse ase sot the tor ho ato and hesed the wanges and has tarde soul oo toren ating the tas thath wethes anterad the to the sos te the sor sos ared sat ta le an sin sess tim sore as hor sould the soun saren sos wange she sos than he he sont ot the ant ote wasetisgit ho what hhe them shis her souse whe has were whis satha thes tathe worid sorte sos what ho theminget te tersind and withe sealesend thers sad he ha san sirisg ate her wesas,, ther hasessand we the sos tase soste hitit him se se sanding on wat oo th mame hor an shas wim sans hoss the hor wat his tead hors the werend tite ther the sante as atin his of withe wons

In [26]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i600_l512.ckpt
Farry this was
taid,
and the said, a mont what he had been so to some and that went say had the hand of to the soult had been to the sat his ant saight of tree troush
stile of the
romstionss and he calle her store too asterted, at she had not aspicuss though, with which she was not that her, whice son the miss time the sened of that was so shim heares him at the prosssed of the mither and and the chinge to has her.

"What his to dees to his that intore that howself, that she sear stonged. He
downt hom sampersside hereed, and her and ansten her
sto the pactiring of his shoule he samped out it, and she wishout at his head he cauld not same, and
homerady onered to had
had had beet it she tow allather one to
the mure the sours, that see ald the messe and and athis to has the peast on his sang of har that with a darstings,
would not ther ho her aloud heard.

"Well you sen the daring that he
had
been seepter, a whonther
to 

In [27]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i1200_l512.ckpt
Farre wan trainten all the parster and somt on
if the collow while the provers of the manthions and
his hand.

She had no dissite the convicult and which he canned in
the stees that he was sacingly with the polters and stenting
at the sondition and the place, and sampling the pectle to see the say sering. The cleat with a stonly three shoot went to ter sincing off in.

"Why did you wear this way a good.

"The seed to so well, the more at her so somether.


An the distonde though a lifter wander would bream out that he croved
her his
all as the sten at a mat warning that if he was a same to be all the peasant at the child of trought."

"Well, to you was to be me that is to
make you tell you with happy
one mides that it's stranging to the began and her, but here," said Stepan
Arkadyevitch. "He chould time the same to
him at the decast that he well
bet indeed thried that happy in the discronce of the place of the simple